# Sets management endpoints root path to /api/v1 instead of /actuator
management:
  endpoints:
    web:
      base-path: "/api/v1"

# Enables H2 web console
spring:
  h2:
    console:
      enabled: "true"
      settings:
        web-allow-others: "true"
  # Changes default db name, username and password
  datasource:
    url: "jdbc:h2:mem:small_cinema_db"
    username: "small_cinema_db_user"
    password: "123sc456"
